field: 74eb36ae-7a26-4e7d-b454-990ec52617f0 # Builder: Content
fieldLayouts:
  2f43cd1f-4b91-4b38-aa35-4ae90d08f2db:
    tabs:
      -
        elements:
          -
            fieldUid: 0a686d89-8754-4f00-a79e-fed75548909d # Images
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1a64748f-2870-4c18-a869-f2b050ede5ba # Image Transform
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0a686d89-8754-4f00-a79e-fed75548909d: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:f1b38495-8096-48fa-9b78-0da345e3295c' # Images
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:6c5fc0dd-cf56-48d8-8af8-88abe763b970' # Files
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:f1b38495-8096-48fa-9b78-0da345e3295c' # Images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: true
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  1a64748f-2870-4c18-a869-f2b050ede5ba: # Image Transform
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imageTransform
    instructions: ''
    name: 'Image Transform'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Landscape
            -
              - value
              - landscape
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Square
            -
              - value
              - square
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Portrait
            -
              - value
              - portrait
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Auto
            -
              - value
              - auto
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: blockImageSlider
name: 'Image Slider'
sortOrder: 9
