field: 74eb36ae-7a26-4e7d-b454-990ec52617f0 # Builder: Content
fieldLayouts:
  a4335b2d-af34-4544-b20a-e4a928a3693c:
    tabs:
      -
        elements:
          -
            fieldUid: 1b37c439-5a32-4e8f-8019-7f6a94593419 # Spacer Variant
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1b37c439-5a32-4e8f-8019-7f6a94593419: # Spacer Variant
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: spacerVariant
    instructions: ''
    name: 'Spacer Variant'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - SM
            -
              - value
              - sm
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - MD
            -
              - value
              - md
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - LG
            -
              - value
              - lg
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - XL
            -
              - value
              - xl
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 2XL
            -
              - value
              - 2xl
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: blockSpacer
name: Spacer
sortOrder: 12
