field: 74eb36ae-7a26-4e7d-b454-990ec52617f0 # Builder: Content
fieldLayouts:
  4423c5be-938a-4871-bd99-52e14a8de079:
    tabs:
      -
        elements:
          -
            fieldUid: f084e099-613d-4405-b600-f4be12d3509b # Divider Variant
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  f084e099-613d-4405-b600-f4be12d3509b: # Divider Variant
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: dividerVariant
    instructions: ''
    name: 'Divider Variant'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - SM
            -
              - value
              - sm
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - MD
            -
              - value
              - md
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - LG
            -
              - value
              - lg
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - XL
            -
              - value
              - xl
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 2XL
            -
              - value
              - 2xl
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: blockDivider
name: Divider
sortOrder: 11
