columnSuffix: mzlozibq
contentColumnType: text
fieldGroup: d383bdc6-fcfa-4652-9155-d7ead2d89f29 # Assets
handle: assetCaption
instructions: ''
name: 'Asset: Caption'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
