columnSuffix: twbwiyps
contentColumnType: text
fieldGroup: d383bdc6-fcfa-4652-9155-d7ead2d89f29 # Assets
handle: assetTitle
instructions: ''
name: 'Asset: Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
